export let houseOfRepMap = {
  "FC/360/FCT": {
    code: "FC/360/FCT",
    name: "Municipal/Bwari",
    race: "house",
    state_code: "FCT",
    state_name: "FCT",
  },
  "FC/242/LA": {
    code: "FC/242/LA",
    name: "Mushin II",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/247/LA": {
    code: "FC/247/LA",
    name: "Oshodi/Isolo II",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/251/LA": {
    code: "FC/251/LA",
    name: "Surulere II",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/328/RV": {
    code: "FC/328/RV",
    name: "Port Harcourt II",
    race: "house",
    state_code: "RI",
    state_name: "Rivers",
  },
  "FC/001/AB": {
    code: "FC/001/AB",
    name: "Aba North/Aba South",
    race: "house",
    state_code: "AB",
    state_name: "Abia",
  },
  "FC/002/AB": {
    code: "FC/002/AB",
    name: "Arochukwu/Ohafia",
    race: "house",
    state_code: "AB",
    state_name: "Abia",
  },
  "FC/003/AB": {
    code: "FC/003/AB",
    name: "Bende",
    race: "house",
    state_code: "AB",
    state_name: "Abia",
  },
  "FC/004/AB": {
    code: "FC/004/AB",
    name: "Isiala Ngwa North/Isiala Ngwa South",
    race: "house",
    state_code: "AB",
    state_name: "Abia",
  },
  "FC/005/AB": {
    code: "FC/005/AB",
    name: "Isuikwuato/Umu-Nneochi",
    race: "house",
    state_code: "AB",
    state_name: "Abia",
  },
  "FC/006/AB": {
    code: "FC/006/AB",
    name: "Obingwa/Ugwunagbo/Osisioma",
    race: "house",
    state_code: "AB",
    state_name: "Abia",
  },
  "FC/007/AB": {
    code: "FC/007/AB",
    name: "Umuahia North/Umuahia South/Ikwuano",
    race: "house",
    state_code: "AB",
    state_name: "Abia",
  },
  "FC/008/AB": {
    code: "FC/008/AB",
    name: "Ukwa East/Ukwa West",
    race: "house",
    state_code: "AB",
    state_name: "Abia",
  },
  "FC/009/AD": {
    code: "FC/009/AD",
    name: "Demsa/Numan/Lamurde",
    race: "house",
    state_code: "AD",
    state_name: "Adamawa",
  },
  "FC/010/AD": {
    code: "FC/010/AD",
    name: "Furore/Song",
    race: "house",
    state_code: "AD",
    state_name: "Adamawa",
  },
  "FC/011/AD": {
    code: "FC/011/AD",
    name: "Mayo Belwa/Ganye/Jada/Toungo",
    race: "house",
    state_code: "AD",
    state_name: "Adamawa",
  },
  "FC/012/AD": {
    code: "FC/012/AD",
    name: "Gombi/Hong",
    race: "house",
    state_code: "AD",
    state_name: "Adamawa",
  },
  "FC/013/AD": {
    code: "FC/013/AD",
    name: "Guyuk/Shelleng",
    race: "house",
    state_code: "AD",
    state_name: "Adamawa",
  },
  "FC/014/AD": {
    code: "FC/014/AD",
    name: "Madagali/Michika",
    race: "house",
    state_code: "AD",
    state_name: "Adamawa",
  },
  "FC/015/AD": {
    code: "FC/015/AD",
    name: "Maiha/Mubi North/Mubi South",
    race: "house",
    state_code: "AD",
    state_name: "Adamawa",
  },
  "FC/016/AD": {
    code: "FC/016/AD",
    name: "Yola North/Yola South/Girei",
    race: "house",
    state_code: "AD",
    state_name: "Adamawa",
  },
  "FC/017/AK": {
    code: "FC/017/AK",
    name: "Abak/Etim Ekpo/Ika",
    race: "house",
    state_code: "AK",
    state_name: "Akwa Ibom",
  },
  "FC/018/AK": {
    code: "FC/018/AK",
    name: "Eket/Onna/Esit Eket/Ibeno",
    race: "house",
    state_code: "AK",
    state_name: "Akwa Ibom",
  },
  "FC/019/AK": {
    code: "FC/019/AK",
    name: "Etinan/Nsit Ibom/Nsit Ubium",
    race: "house",
    state_code: "AK",
    state_name: "Akwa Ibom",
  },
  "FC/020/AK": {
    code: "FC/020/AK",
    name: "Ikono/Ini",
    race: "house",
    state_code: "AK",
    state_name: "Akwa Ibom",
  },
  "FC/021/AK": {
    code: "FC/021/AK",
    name: "Ikot Abasi/Mkpat Enin/Eastern Obolo",
    race: "house",
    state_code: "AK",
    state_name: "Akwa Ibom",
  },
  "FC/022/AK": {
    code: "FC/022/AK",
    name: "Ikot Ekpene/Essien Udim/Obot Akara",
    race: "house",
    state_code: "AK",
    state_name: "Akwa Ibom",
  },
  "FC/023/AK": {
    code: "FC/023/AK",
    name: "Itu/Ibiono Ibom",
    race: "house",
    state_code: "AK",
    state_name: "Akwa Ibom",
  },
  "FC/024/AK": {
    code: "FC/024/AK",
    name: "Oron/Mbo/Okobo/Udung Uko/Urue Offong/Oruko",
    race: "house",
    state_code: "AK",
    state_name: "Akwa Ibom",
  },
  "FC/025/AK": {
    code: "FC/025/AK",
    name: "Ukanafun/Oruk Anam",
    race: "house",
    state_code: "AK",
    state_name: "Akwa Ibom",
  },
  "FC/026/AK": {
    code: "FC/026/AK",
    name: "Uyo/Uruan/Nsit Atai/Ibesikpo Asutan",
    race: "house",
    state_code: "AK",
    state_name: "Akwa Ibom",
  },
  "FC/027/AN": {
    code: "FC/027/AN",
    name: "Anambra East/Anambra West",
    race: "house",
    state_code: "AN",
    state_name: "Anambra",
  },
  "FC/028/AN": {
    code: "FC/028/AN",
    name: "Onitsha North/Onitsha South",
    race: "house",
    state_code: "AN",
    state_name: "Anambra",
  },
  "FC/029/AN": {
    code: "FC/029/AN",
    name: "Ogbaru",
    race: "house",
    state_code: "AN",
    state_name: "Anambra",
  },
  "FC/030/AN": {
    code: "FC/030/AN",
    name: "Aguata",
    race: "house",
    state_code: "AN",
    state_name: "Anambra",
  },
  "FC/031/AN": {
    code: "FC/031/AN",
    name: "Oyi/Ayamelum",
    race: "house",
    state_code: "AN",
    state_name: "Anambra",
  },
  "FC/032/AN": {
    code: "FC/032/AN",
    name: "Awka North/Awka South",
    race: "house",
    state_code: "AN",
    state_name: "Anambra",
  },
  "FC/033/AN": {
    code: "FC/033/AN",
    name: "Njikoka/Dunukofia/Anaocha",
    race: "house",
    state_code: "AN",
    state_name: "Anambra",
  },
  "FC/034/AN": {
    code: "FC/034/AN",
    name: "Idemili North/Idemili South",
    race: "house",
    state_code: "AN",
    state_name: "Anambra",
  },
  "FC/035/AN": {
    code: "FC/035/AN",
    name: "Ihiala",
    race: "house",
    state_code: "AN",
    state_name: "Anambra",
  },
  "FC/036/AN": {
    code: "FC/036/AN",
    name: "Nnewi North/Nnewi South/Ekwusigo",
    race: "house",
    state_code: "AN",
    state_name: "Anambra",
  },
  "FC/037/AN": {
    code: "FC/037/AN",
    name: "Orumba North/Orumba South",
    race: "house",
    state_code: "AN",
    state_name: "Anambra",
  },
  "FC/038/BA": {
    code: "FC/038/BA",
    name: "Alkaleri/Kirfi",
    race: "house",
    state_code: "BA",
    state_name: "Bauchi",
  },
  "FC/039/BA": {
    code: "FC/039/BA",
    name: "Bauchi",
    race: "house",
    state_code: "BA",
    state_name: "Bauchi",
  },
  "FC/040/BA": {
    code: "FC/040/BA",
    name: "Bogoro/Dass/Tafawa Balewa",
    race: "house",
    state_code: "BA",
    state_name: "Bauchi",
  },
  "FC/041/BA": {
    code: "FC/041/BA",
    name: "Toro",
    race: "house",
    state_code: "BA",
    state_name: "Bauchi",
  },
  "FC/042/BA": {
    code: "FC/042/BA",
    name: "Ningi/Warji",
    race: "house",
    state_code: "BA",
    state_name: "Bauchi",
  },
  "FC/043/BA": {
    code: "FC/043/BA",
    name: "Darazo/Gunjuwa",
    race: "house",
    state_code: "BA",
    state_name: "Bauchi",
  },
  "FC/044/BA": {
    code: "FC/044/BA",
    name: "Misau/Dambam",
    race: "house",
    state_code: "BA",
    state_name: "Bauchi",
  },
  "FC/045/BA": {
    code: "FC/045/BA",
    name: "Zaki",
    race: "house",
    state_code: "BA",
    state_name: "Bauchi",
  },
  "FC/046/BA": {
    code: "FC/046/BA",
    name: "Gamawa",
    race: "house",
    state_code: "BA",
    state_name: "Bauchi",
  },
  "FC/047/BA": {
    code: "FC/047/BA",
    name: "Jamaare/Itas-Gadau",
    race: "house",
    state_code: "BA",
    state_name: "Bauchi",
  },
  "FC/048/BA": {
    code: "FC/048/BA",
    name: "Shira/Giade",
    race: "house",
    state_code: "BA",
    state_name: "Bauchi",
  },
  "FC/049/BA": {
    code: "FC/049/BA",
    name: "Katagum",
    race: "house",
    state_code: "BA",
    state_name: "Bauchi",
  },
  "FC/051/BY": {
    code: "FC/051/BY",
    name: "Ogbia",
    race: "house",
    state_code: "BY",
    state_name: "Bayelsa",
  },
  "FC/052/BY": {
    code: "FC/052/BY",
    name: "Sagbama/Ekeremor",
    race: "house",
    state_code: "BY",
    state_name: "Bayelsa",
  },
  "FC/053/BY": {
    code: "FC/053/BY",
    name: "Southern Ijaw",
    race: "house",
    state_code: "BY",
    state_name: "Bayelsa",
  },
  "FC/054/BY": {
    code: "FC/054/BY",
    name: "Yenagoa/Kolokuna/Opokuma",
    race: "house",
    state_code: "BY",
    state_name: "Bayelsa",
  },
  "FC/055/BN": {
    code: "FC/055/BN",
    name: "Ado/Obadigbo/Okpokwu",
    race: "house",
    state_code: "BE",
    state_name: "Benue",
  },
  "FC/056/BN": {
    code: "FC/056/BN",
    name: "Apa/Agatu",
    race: "house",
    state_code: "BE",
    state_name: "Benue",
  },
  "FC/057/BN": {
    code: "FC/057/BN",
    name: "Buruku",
    race: "house",
    state_code: "BE",
    state_name: "Benue",
  },
  "FC/050/BY": {
    code: "FC/050/BY",
    name: "Brass/Nembe",
    race: "house",
    state_code: "BY",
    state_name: "Bayelsa",
  },
  "FC/058/BN": {
    code: "FC/058/BN",
    name: "Gboko/Tarka",
    race: "house",
    state_code: "BE",
    state_name: "Benue",
  },
  "FC/059/BN": {
    code: "FC/059/BN",
    name: "Guma/Makurdi",
    race: "house",
    state_code: "BE",
    state_name: "Benue",
  },
  "FC/060/BN": {
    code: "FC/060/BN",
    name: "Gwer East/Gwer West",
    race: "house",
    state_code: "BE",
    state_name: "Benue",
  },
  "FC/061/BN": {
    code: "FC/061/BN",
    name: "Katsina-Ala/Ukum/Logo",
    race: "house",
    state_code: "BE",
    state_name: "Benue",
  },
  "FC/062/BN": {
    code: "FC/062/BN",
    name: "Konshisha/Vandeikya",
    race: "house",
    state_code: "BE",
    state_name: "Benue",
  },
  "FC/063/BN": {
    code: "FC/063/BN",
    name: "Kwande/Ushongo",
    race: "house",
    state_code: "BE",
    state_name: "Benue",
  },
  "FC/064/BN": {
    code: "FC/064/BN",
    name: "Oju/Obi",
    race: "house",
    state_code: "BE",
    state_name: "Benue",
  },
  "FC/065/BN": {
    code: "FC/065/BN",
    name: "Otukpo/Ohimini",
    race: "house",
    state_code: "BE",
    state_name: "Benue",
  },
  "FC/066/BO": {
    code: "FC/066/BO",
    name: "Askira-Uba/Hawul",
    race: "house",
    state_code: "BO",
    state_name: "Borno",
  },
  "FC/067/BO": {
    code: "FC/067/BO",
    name: "Bama/Ngala/Kala-Balge",
    race: "house",
    state_code: "BO",
    state_name: "Borno",
  },
  "FC/068/BO": {
    code: "FC/068/BO",
    name: "Biu/Kwaya-Kusar Shani/Bayo",
    race: "house",
    state_code: "BO",
    state_name: "Borno",
  },
  "FC/069/BO": {
    code: "FC/069/BO",
    name: "Dikwa/Mafa/Konduga",
    race: "house",
    state_code: "BO",
    state_name: "Borno",
  },
  "FC/070/BO": {
    code: "FC/070/BO",
    name: "Damboa/Gwoza/Chibok",
    race: "house",
    state_code: "BO",
    state_name: "Borno",
  },
  "FC/071/BO": {
    code: "FC/071/BO",
    name: "Kaga/Gubio/Magumeri",
    race: "house",
    state_code: "BO",
    state_name: "Borno",
  },
  "FC/072/BO": {
    code: "FC/072/BO",
    name: "Monguno/Nganzai/Marte",
    race: "house",
    state_code: "BO",
    state_name: "Borno",
  },
  "FC/073/BO": {
    code: "FC/073/BO",
    name: "Kukawa/Mobbar/Abadam/Guzamali",
    race: "house",
    state_code: "BO",
    state_name: "Borno",
  },
  "FC/074/BO": {
    code: "FC/074/BO",
    name: "Maiduguri Metropolitan",
    race: "house",
    state_code: "BO",
    state_name: "Borno",
  },
  "FC/075/BO": {
    code: "FC/075/BO",
    name: "Jere",
    race: "house",
    state_code: "BO",
    state_name: "Borno",
  },
  "FC/076/CR": {
    code: "FC/076/CR",
    name: "Yakurr/Abi",
    race: "house",
    state_code: "CR",
    state_name: "Cross River",
  },
  "FC/077/CR": {
    code: "FC/077/CR",
    name: "Akamkpa/Biase",
    race: "house",
    state_code: "CR",
    state_name: "Cross River",
  },
  "FC/078/CR": {
    code: "FC/078/CR",
    name: "Boki/Ikom",
    race: "house",
    state_code: "CR",
    state_name: "Cross River",
  },
  "FC/079/CR": {
    code: "FC/079/CR",
    name: "Calabar South/Akpabuyo/Bakassi",
    race: "house",
    state_code: "CR",
    state_name: "Cross River",
  },
  "FC/080/CR": {
    code: "FC/080/CR",
    name: "Calabar Municipal/Odukpani",
    race: "house",
    state_code: "CR",
    state_name: "Cross River",
  },
  "FC/081/CR": {
    code: "FC/081/CR",
    name: "Obanliku/Obudu/Bekwarra",
    race: "house",
    state_code: "CR",
    state_name: "Cross River",
  },
  "FC/082/CR": {
    code: "FC/082/CR",
    name: "Obubra/Etung",
    race: "house",
    state_code: "CR",
    state_name: "Cross River",
  },
  "FC/083/CR": {
    code: "FC/083/CR",
    name: "Ogoja/Yala",
    race: "house",
    state_code: "CR",
    state_name: "Cross River",
  },
  "FC/084/DT": {
    code: "FC/084/DT",
    name: "Aniocha North/Aniocha South/Oshimili North South",
    race: "house",
    state_code: "DE",
    state_name: "Delta",
  },
  "FC/085/DT": {
    code: "FC/085/DT",
    name: "Bomadi/Patani",
    race: "house",
    state_code: "DE",
    state_name: "Delta",
  },
  "FC/086/DT": {
    code: "FC/086/DT",
    name: "Ethiope East/Ethiope West",
    race: "house",
    state_code: "DE",
    state_name: "Delta",
  },
  "FC/087/DT": {
    code: "FC/087/DT",
    name: "Ika North East/Ika South",
    race: "house",
    state_code: "DE",
    state_name: "Delta",
  },
  "FC/088/DT": {
    code: "FC/088/DT",
    name: "Isoko North/Isoko South",
    race: "house",
    state_code: "DE",
    state_name: "Delta",
  },
  "FC/089/DT": {
    code: "FC/089/DT",
    name: "Nkokwa East/Ndokwa West/Ukwuani",
    race: "house",
    state_code: "DE",
    state_name: "Delta",
  },
  "FC/090/DT": {
    code: "FC/090/DT",
    name: "Okpe/Sapele/Uvwie",
    race: "house",
    state_code: "DE",
    state_name: "Delta",
  },
  "FC/091/DT": {
    code: "FC/091/DT",
    name: "Burutu",
    race: "house",
    state_code: "DE",
    state_name: "Delta",
  },
  "FC/092/DT": {
    code: "FC/092/DT",
    name: "Ughelli North Ughelli South/Udu",
    race: "house",
    state_code: "DE",
    state_name: "Delta",
  },
  "FC/093/DT": {
    code: "FC/093/DT",
    name: "Warri North/Warri South/Warri South West",
    race: "house",
    state_code: "DE",
    state_name: "Delta",
  },
  "FC/094/EB": {
    code: "FC/094/EB",
    name: "Ebonyi/Ohaukwu",
    race: "house",
    state_code: "EB",
    state_name: "Ebonyi",
  },
  "FC/095/EB": {
    code: "FC/095/EB",
    name: "Abakaliki/Izzi",
    race: "house",
    state_code: "EB",
    state_name: "Ebonyi",
  },
  "FC/096/EB": {
    code: "FC/096/EB",
    name: "Ezza North/Ishielu",
    race: "house",
    state_code: "EB",
    state_name: "Ebonyi",
  },
  "FC/097/EB": {
    code: "FC/097/EB",
    name: "Ezza South/Ikwo",
    race: "house",
    state_code: "EB",
    state_name: "Ebonyi",
  },
  "FC/098/EB": {
    code: "FC/098/EB",
    name: "Ivo-Ohaozara/Onicha",
    race: "house",
    state_code: "EB",
    state_name: "Ebonyi",
  },
  "FC/099/EB": {
    code: "FC/099/EB",
    name: "Afikpo North/Afikpo South",
    race: "house",
    state_code: "EB",
    state_name: "Ebonyi",
  },
  "FC/100/ED": {
    code: "FC/100/ED",
    name: "Akoko-Edo",
    race: "house",
    state_code: "ED",
    state_name: "Edo",
  },
  "FC/101/ED": {
    code: "FC/101/ED",
    name: "Esan Central/Esan South/Igueben",
    race: "house",
    state_code: "ED",
    state_name: "Edo",
  },
  "FC/102/ED": {
    code: "FC/102/ED",
    name: "Esan North East/Esan South East",
    race: "house",
    state_code: "ED",
    state_name: "Edo",
  },
  "FC/103/ED": {
    code: "FC/103/ED",
    name: "Etsako East/Etsako West/Etsako Central",
    race: "house",
    state_code: "ED",
    state_name: "Edo",
  },
  "FC/104/ED": {
    code: "FC/104/ED",
    name: "Egor/Ikpoba-Okha",
    race: "house",
    state_code: "ED",
    state_name: "Edo",
  },
  "FC/105/ED": {
    code: "FC/105/ED",
    name: "Oredo",
    race: "house",
    state_code: "ED",
    state_name: "Edo",
  },
  "FC/106/ED": {
    code: "FC/106/ED",
    name: "Orhionmwon/Uhunmwonde",
    race: "house",
    state_code: "ED",
    state_name: "Edo",
  },
  "FC/107/ED": {
    code: "FC/107/ED",
    name: "Ovia North East/Ovia South West",
    race: "house",
    state_code: "ED",
    state_name: "Edo",
  },
  "FC/108/ED": {
    code: "FC/108/ED",
    name: "Owan East/Owan West",
    race: "house",
    state_code: "ED",
    state_name: "Edo",
  },
  "FC/109/EK": {
    code: "FC/109/EK",
    name: "Ado Ekiti/Irepodun/Ifelodun",
    race: "house",
    state_code: "EK",
    state_name: "Ekiti",
  },
  "FC/110/EK": {
    code: "FC/110/EK",
    name: "Ekiti South West/Ikere/Orun/Ise",
    race: "house",
    state_code: "EK",
    state_name: "Ekiti",
  },
  "FC/111/EK": {
    code: "FC/111/EK",
    name: "Emure/Gbonyin/Ekiti East",
    race: "house",
    state_code: "EK",
    state_name: "Ekiti",
  },
  "FC/112/EK": {
    code: "FC/112/EK",
    name: "Ido/Osi Moba/Ilejeme",
    race: "house",
    state_code: "EK",
    state_name: "Ekiti",
  },
  "FC/113/EK": {
    code: "FC/113/EK",
    name: "Ijero/Ekiti West/Efon",
    race: "house",
    state_code: "EK",
    state_name: "Ekiti",
  },
  "FC/114/EK": {
    code: "FC/114/EK",
    name: "Ikole/Oye",
    race: "house",
    state_code: "EK",
    state_name: "Ekiti",
  },
  "FC/115/EN": {
    code: "FC/115/EN",
    name: "Aninri/Awgu/Oji River",
    race: "house",
    state_code: "EN",
    state_name: "Enugu",
  },
  "FC/116/EN": {
    code: "FC/116/EN",
    name: "Enugu East/Isi Uzo",
    race: "house",
    state_code: "EN",
    state_name: "Enugu",
  },
  "FC/117/EN": {
    code: "FC/117/EN",
    name: "Enugu North/Enugu South",
    race: "house",
    state_code: "EN",
    state_name: "Enugu",
  },
  "FC/118/EN": {
    code: "FC/118/EN",
    name: "Ezeagu/Udi",
    race: "house",
    state_code: "EN",
    state_name: "Enugu",
  },
  "FC/119/EN": {
    code: "FC/119/EN",
    name: "Igbo-Etiti/Uzo-Uwani",
    race: "house",
    state_code: "EN",
    state_name: "Enugu",
  },
  "FC/120/EN": {
    code: "FC/120/EN",
    name: "Igbo-Eze North/Udenu",
    race: "house",
    state_code: "EN",
    state_name: "Enugu",
  },
  "FC/121/EN": {
    code: "FC/121/EN",
    name: "Nkanu East/Nkanu West",
    race: "house",
    state_code: "EN",
    state_name: "Enugu",
  },
  "FC/122/EN": {
    code: "FC/122/EN",
    name: "Nsukka/Igbo-Eze South",
    race: "house",
    state_code: "EN",
    state_name: "Enugu",
  },
  "FC/123/GM": {
    code: "FC/123/GM",
    name: "Akko",
    race: "house",
    state_code: "GO",
    state_name: "Gombe",
  },
  "FC/124/GM": {
    code: "FC/124/GM",
    name: "Yamaltu/Deba",
    race: "house",
    state_code: "GO",
    state_name: "Gombe",
  },
  "FC/125/GM": {
    code: "FC/125/GM",
    name: "Balanga/Billiri",
    race: "house",
    state_code: "GO",
    state_name: "Gombe",
  },
  "FC/126/GM": {
    code: "FC/126/GM",
    name: "Kaltungo/Shongom",
    race: "house",
    state_code: "GO",
    state_name: "Gombe",
  },
  "FC/127/GM": {
    code: "FC/127/GM",
    name: "Gombe/Kwami/Funakaye",
    race: "house",
    state_code: "GO",
    state_name: "Gombe",
  },
  "FC/128/GM": {
    code: "FC/128/GM",
    name: "Dukku/Nafada",
    race: "house",
    state_code: "GO",
    state_name: "Gombe",
  },
  "FC/129/IM": {
    code: "FC/129/IM",
    name: "Ehime Mbano/Ihite-Uboma/Obowo",
    race: "house",
    state_code: "IM",
    state_name: "Imo",
  },
  "FC/130/IM": {
    code: "FC/130/IM",
    name: "Isiala Mbano/Okigwe/Onuimo",
    race: "house",
    state_code: "IM",
    state_name: "Imo",
  },
  "FC/131/IM": {
    code: "FC/131/IM",
    name: "Ideato North/Ideato South",
    race: "house",
    state_code: "IM",
    state_name: "Imo",
  },
  "FC/132/IM": {
    code: "FC/132/IM",
    name: "Isu/Njaba/Nkwerre/Nwangele",
    race: "house",
    state_code: "IM",
    state_name: "Imo",
  },
  "FC/133/IM": {
    code: "FC/133/IM",
    name: "Oguta/Ohaji-Egbema/Oru West",
    race: "house",
    state_code: "IM",
    state_name: "Imo",
  },
  "FC/134/IM": {
    code: "FC/134/IM",
    name: "Oru East/Orsu/Orlu",
    race: "house",
    state_code: "IM",
    state_name: "Imo",
  },
  "FC/135/IM": {
    code: "FC/135/IM",
    name: "Aboh Mbaise/Ngor Okpala",
    race: "house",
    state_code: "IM",
    state_name: "Imo",
  },
  "FC/136/IM": {
    code: "FC/136/IM",
    name: "Ahiazu Mbaise/Ezinihitte",
    race: "house",
    state_code: "IM",
    state_name: "Imo",
  },
  "FC/137/IM": {
    code: "FC/137/IM",
    name: "Ikeduru/Mbaitoli",
    race: "house",
    state_code: "IM",
    state_name: "Imo",
  },
  "FC/359/FCT": {
    code: "FC/359/FCT",
    name: "Abaji/Gwagwalada/Kwali/Kuje",
    race: "house",
    state_code: "FCT",
    state_name: "FCT",
  },
  "FC/138/IM": {
    code: "FC/138/IM",
    name: "Owerri Municipal/Owerri North/Owerri West",
    race: "house",
    state_code: "IM",
    state_name: "Imo",
  },
  "FC/139/JG": {
    code: "FC/139/JG",
    name: "Babura/Garki",
    race: "house",
    state_code: "JI",
    state_name: "Jigawa",
  },
  "FC/140/JG": {
    code: "FC/140/JG",
    name: "Birnin Kudu/Buji",
    race: "house",
    state_code: "JI",
    state_name: "Jigawa",
  },
  "FC/141/JG": {
    code: "FC/141/JG",
    name: "Birniwa Guri/Kirikasamma",
    race: "house",
    state_code: "JI",
    state_name: "Jigawa",
  },
  "FC/142/JG": {
    code: "FC/142/JG",
    name: "Dutse/Kiyawa",
    race: "house",
    state_code: "JI",
    state_name: "Jigawa",
  },
  "FC/143/JG": {
    code: "FC/143/JG",
    name: "Gwaram",
    race: "house",
    state_code: "JI",
    state_name: "Jigawa",
  },
  "FC/144/JG": {
    code: "FC/144/JG",
    name: "Gumel/Maigatari/Sule Tankarkar/Gagarawa",
    race: "house",
    state_code: "JI",
    state_name: "Jigawa",
  },
  "FC/145/JG": {
    code: "FC/145/JG",
    name: "Hadejia/Kafin Hausa",
    race: "house",
    state_code: "JI",
    state_name: "Jigawa",
  },
  "FC/146/JG": {
    code: "FC/146/JG",
    name: "Jahun/Miga",
    race: "house",
    state_code: "JI",
    state_name: "Jigawa",
  },
  "FC/147/JG": {
    code: "FC/147/JG",
    name: "Mallam Madori/Kaugama",
    race: "house",
    state_code: "JI",
    state_name: "Jigawa",
  },
  "FC/148/JG": {
    code: "FC/148/JG",
    name: "Kazaure/Roni/Gwiwa/Yankwashi",
    race: "house",
    state_code: "JI",
    state_name: "Jigawa",
  },
  "FC/149/JG": {
    code: "FC/149/JG",
    name: "Ringim/Taura",
    race: "house",
    state_code: "JI",
    state_name: "Jigawa",
  },
  "FC/150/KD": {
    code: "FC/150/KD",
    name: "Kaduna North",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/151/KD": {
    code: "FC/151/KD",
    name: "Zaria",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/152/KD": {
    code: "FC/152/KD",
    name: "Soba",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/153/KD": {
    code: "FC/153/KD",
    name: "Igabi",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/154/KD": {
    code: "FC/154/KD",
    name: "Ikara/Kubau",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/155/KD": {
    code: "FC/155/KD",
    name: "Makarfi/Kudan",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/156/KD": {
    code: "FC/156/KD",
    name: "Lere",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/157/KD": {
    code: "FC/157/KD",
    name: "Kachia/Kagarko",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/158/KD": {
    code: "FC/158/KD",
    name: "Chikun/Kajuru",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/159/KD": {
    code: "FC/159/KD",
    name: "Jemaa/Sanga",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/160/KD": {
    code: "FC/160/KD",
    name: "Birnin Gwari/Giwa",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/161/KD": {
    code: "FC/161/KD",
    name: "Sabon Gari",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/162/KD": {
    code: "FC/162/KD",
    name: "Kaduna South",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/163/KD": {
    code: "FC/163/KD",
    name: "Kaura",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/164/KD": {
    code: "FC/164/KD",
    name: "Kauru",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/165/KD": {
    code: "FC/165/KD",
    name: "Zangon Kataf/Jaba",
    race: "house",
    state_code: "KD",
    state_name: "Kaduna",
  },
  "FC/166/KN": {
    code: "FC/166/KN",
    name: "Alabasu/Gaya/Ajingi",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/167/KN": {
    code: "FC/167/KN",
    name: "Shanono/Bagwai",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/168/KN": {
    code: "FC/168/KN",
    name: "Bebeji/Kiru",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/169/KN": {
    code: "FC/169/KN",
    name: "Bichi",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/170/KN": {
    code: "FC/170/KN",
    name: "Rano/Bunkure/Kibiya",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/171/KN": {
    code: "FC/171/KN",
    name: "Dala",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/172/KN": {
    code: "FC/172/KN",
    name: "Gwale",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/173/KN": {
    code: "FC/173/KN",
    name: "Dambatta/Makoda",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/174/KN": {
    code: "FC/174/KN",
    name: "Dawakin Kudu/Warawa",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/175/KN": {
    code: "FC/175/KN",
    name: "Dawakin Tofa/Tofa/Rimin Gado",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/176/KN": {
    code: "FC/176/KN",
    name: "Doguwa/Tudun Wada",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/177/KN": {
    code: "FC/177/KN",
    name: "Gezawa/Gabasawa",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/178/KN": {
    code: "FC/178/KN",
    name: "Gwarzo/Ikabo",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/179/KN": {
    code: "FC/179/KN",
    name: "Municipal",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/180/KN": {
    code: "FC/180/KN",
    name: "Tarauni",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/181/KN": {
    code: "FC/181/KN",
    name: "Karaye/Rogo",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/182/KN": {
    code: "FC/182/KN",
    name: "Kumbotso",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/183/KN": {
    code: "FC/183/KN",
    name: "Kura/Madobi/Garun Mallam",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/184/KN": {
    code: "FC/184/KN",
    name: "Nassarawa",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/185/KN": {
    code: "FC/185/KN",
    name: "Fagge",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/186/KN": {
    code: "FC/186/KN",
    name: "Sumaila/Takai",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/187/KN": {
    code: "FC/187/KN",
    name: "Minjibir/Ungogo",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/188/KN": {
    code: "FC/188/KN",
    name: "Tsanyawa/Kunchi",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/189/KN": {
    code: "FC/189/KN",
    name: "Wudil/Garko",
    race: "house",
    state_code: "KN",
    state_name: "Kano",
  },
  "FC/190/KT": {
    code: "FC/190/KT",
    name: "Bakori/Danja",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/191/KT": {
    code: "FC/191/KT",
    name: "Batagarawa/Charanchi/Rimi",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/192/KT": {
    code: "FC/192/KT",
    name: "Batsari/Safana/Danmusa",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/193/KT": {
    code: "FC/193/KT",
    name: "Bindawa/Mani",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/194/KT": {
    code: "FC/194/KT",
    name: "Daura/Sandamu/Maiadua",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/195/KT": {
    code: "FC/195/KT",
    name: "Dutsin-Ma/Kurfi",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/196/KT": {
    code: "FC/196/KT",
    name: "Faskari/Kankara/Sabuwa",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/197/KT": {
    code: "FC/197/KT",
    name: "Funtua/Dandume",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/198/KT": {
    code: "FC/198/KT",
    name: "Ingawa/Kankia/Kusada",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/199/KT": {
    code: "FC/199/KT",
    name: "Jibia/Kaita",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/200/KT": {
    code: "FC/200/KT",
    name: "Malumfashi/Kafur",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/201/KT": {
    code: "FC/201/KT",
    name: "Katsina",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/202/KT": {
    code: "FC/202/KT",
    name: "Mashi/Dutsi",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/203/KT": {
    code: "FC/203/KT",
    name: "Matazu/Musawa",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/204/KT": {
    code: "FC/204/KT",
    name: "Zango/Baure",
    race: "house",
    state_code: "KT",
    state_name: "Katsina",
  },
  "FC/205/KB": {
    code: "FC/205/KB",
    name: "Arewa/Dandi",
    race: "house",
    state_code: "KE",
    state_name: "Kebbi",
  },
  "FC/206/KB": {
    code: "FC/206/KB",
    name: "Argungu/Augie",
    race: "house",
    state_code: "KE",
    state_name: "Kebbi",
  },
  "FC/207/KB": {
    code: "FC/207/KB",
    name: "Bagudo/Suru",
    race: "house",
    state_code: "KE",
    state_name: "Kebbi",
  },
  "FC/208/KB": {
    code: "FC/208/KB",
    name: "Bunza/Birnin Kebbi/Kalgo",
    race: "house",
    state_code: "KE",
    state_name: "Kebbi",
  },
  "FC/209/KB": {
    code: "FC/209/KB",
    name: "Aleiro/Gwandu/Jega",
    race: "house",
    state_code: "KE",
    state_name: "Kebbi",
  },
  "FC/210/KB": {
    code: "FC/210/KB",
    name: "Koko-Besse/Maiyama",
    race: "house",
    state_code: "KE",
    state_name: "Kebbi",
  },
  "FC/211/KB": {
    code: "FC/211/KB",
    name: "Fakai/Sakaba/Wasagu/Danko/Zuru",
    race: "house",
    state_code: "KE",
    state_name: "Kebbi",
  },
  "FC/212/KB": {
    code: "FC/212/KB",
    name: "Ngaski/Shanga/Yauri",
    race: "house",
    state_code: "KE",
    state_name: "Kebbi",
  },
  "FC/213/KG": {
    code: "FC/213/KG",
    name: "Adavi/Okehi",
    race: "house",
    state_code: "KO",
    state_name: "Kogi",
  },
  "FC/214/KG": {
    code: "FC/214/KG",
    name: "Ankpa/Omala/Olamaboro",
    race: "house",
    state_code: "KO",
    state_name: "Kogi",
  },
  "FC/215/KG": {
    code: "FC/215/KG",
    name: "Bassa/Dekina",
    race: "house",
    state_code: "KO",
    state_name: "Kogi",
  },
  "FC/216/KG": {
    code: "FC/216/KG",
    name: "Idah/Igalamela Odolu/Ibaji/Ofu",
    race: "house",
    state_code: "KO",
    state_name: "Kogi",
  },
  "FC/217/KG": {
    code: "FC/217/KG",
    name: "Ijumu/Kabba-Bunu",
    race: "house",
    state_code: "KO",
    state_name: "Kogi",
  },
  "FC/218/KG": {
    code: "FC/218/KG",
    name: "Ajaokuta",
    race: "house",
    state_code: "KO",
    state_name: "Kogi",
  },
  "FC/219/KG": {
    code: "FC/219/KG",
    name: "Kogi Lokoja/Kogi Kk",
    race: "house",
    state_code: "KO",
    state_name: "Kogi",
  },
  "FC/220/KG": {
    code: "FC/220/KG",
    name: "Okene/Ogori-Magogo",
    race: "house",
    state_code: "KO",
    state_name: "Kogi",
  },
  "FC/221/KG": {
    code: "FC/221/KG",
    name: "Yagba East/Yagba West/Mopamuro",
    race: "house",
    state_code: "KO",
    state_name: "Kogi",
  },
  "FC/222/KW": {
    code: "FC/222/KW",
    name: "Baruten/Kaiama",
    race: "house",
    state_code: "KW",
    state_name: "Kwara",
  },
  "FC/223/KW": {
    code: "FC/223/KW",
    name: "Edu/Moro/Pategi",
    race: "house",
    state_code: "KW",
    state_name: "Kwara",
  },
  "FC/224/KW": {
    code: "FC/224/KW",
    name: "Ekiti/Isin/Irepodun/Oke-Ero",
    race: "house",
    state_code: "KW",
    state_name: "Kwara",
  },
  "FC/225/KW": {
    code: "FC/225/KW",
    name: "Ilorin East/Ilorin South",
    race: "house",
    state_code: "KW",
    state_name: "Kwara",
  },
  "FC/226/KW": {
    code: "FC/226/KW",
    name: "Ilorin West/Asa",
    race: "house",
    state_code: "KW",
    state_name: "Kwara",
  },
  "FC/227/KW": {
    code: "FC/227/KW",
    name: "Ifelodun/Offa/Oyun",
    race: "house",
    state_code: "KW",
    state_name: "Kwara",
  },
  "FC/228/LA": {
    code: "FC/228/LA",
    name: "Agege",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/229/LA": {
    code: "FC/229/LA",
    name: "Ifako/Ijaiye",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/230/LA": {
    code: "FC/230/LA",
    name: "Alimosho",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/231/LA": {
    code: "FC/231/LA",
    name: "Badagry",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/232/LA": {
    code: "FC/232/LA",
    name: "Epe",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/233/LA": {
    code: "FC/233/LA",
    name: "Ibeju Lekki",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/234/LA": {
    code: "FC/234/LA",
    name: "Eti-Osa",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/235/LA": {
    code: "FC/235/LA",
    name: "Apapa",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/236/LA": {
    code: "FC/236/LA",
    name: "Ikeja",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/237/LA": {
    code: "FC/237/LA",
    name: "Ikorodu",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/238/LA": {
    code: "FC/238/LA",
    name: "Lagos Island I",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/240/LA": {
    code: "FC/240/LA",
    name: "Lagos Mainland",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/241/LA": {
    code: "FC/241/LA",
    name: "Mushin I",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/243/LA": {
    code: "FC/243/LA",
    name: "Ojo",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/244/LA": {
    code: "FC/244/LA",
    name: "Amuwo-Odofin",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/245/LA": {
    code: "FC/245/LA",
    name: "Ajeromi/Ifelodun",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/246/LA": {
    code: "FC/246/LA",
    name: "Oshodi/Isolo I",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/248/LA": {
    code: "FC/248/LA",
    name: "Shomolu",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/249/LA": {
    code: "FC/249/LA",
    name: "Kosofe",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/250/LA": {
    code: "FC/250/LA",
    name: "Surulere I",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/252/NW": {
    code: "FC/252/NW",
    name: "Akwanga/Nassarawa Eggon/Wamba",
    race: "house",
    state_code: "NA",
    state_name: "Nasarawa",
  },
  "FC/253/NW": {
    code: "FC/253/NW",
    name: "Awe/Doma/Keana",
    race: "house",
    state_code: "NA",
    state_name: "Nasarawa",
  },
  "FC/254/NW": {
    code: "FC/254/NW",
    name: "Keffi/Karu/Kokona",
    race: "house",
    state_code: "NA",
    state_name: "Nasarawa",
  },
  "FC/255/NW": {
    code: "FC/255/NW",
    name: "Lafia/Obi",
    race: "house",
    state_code: "NA",
    state_name: "Nasarawa",
  },
  "FC/256/NW": {
    code: "FC/256/NW",
    name: "Nassarawa/Toto",
    race: "house",
    state_code: "NA",
    state_name: "Nasarawa",
  },
  "FC/257/NG": {
    code: "FC/257/NG",
    name: "Agaie/Lapai",
    race: "house",
    state_code: "NI",
    state_name: "Niger",
  },
  "FC/258/NG": {
    code: "FC/258/NG",
    name: "Agwara/Borgu",
    race: "house",
    state_code: "NI",
    state_name: "Niger",
  },
  "FC/259/NG": {
    code: "FC/259/NG",
    name: "Bida/Gbako/Katcha",
    race: "house",
    state_code: "NI",
    state_name: "Niger",
  },
  "FC/260/NG": {
    code: "FC/260/NG",
    name: "Booso/Paikoro",
    race: "house",
    state_code: "NI",
    state_name: "Niger",
  },
  "FC/261/NG": {
    code: "FC/261/NG",
    name: "Chanchaga",
    race: "house",
    state_code: "NI",
    state_name: "Niger",
  },
  "FC/262/NG": {
    code: "FC/262/NG",
    name: "Gurara/Suleja/Tapa",
    race: "house",
    state_code: "NI",
    state_name: "Niger",
  },
  "FC/263/NG": {
    code: "FC/263/NG",
    name: "Lavun/Mokwa/Edati",
    race: "house",
    state_code: "NI",
    state_name: "Niger",
  },
  "FC/264/NG": {
    code: "FC/264/NG",
    name: "Magama/Rijau",
    race: "house",
    state_code: "NI",
    state_name: "Niger",
  },
  "FC/265/NG": {
    code: "FC/265/NG",
    name: "Kontagora/Wushishi/Mariga/Mashegu",
    race: "house",
    state_code: "NI",
    state_name: "Niger",
  },
  "FC/266/NG": {
    code: "FC/266/NG",
    name: "Shiroro/Rafi/Munya",
    race: "house",
    state_code: "NI",
    state_name: "Niger",
  },
  "FC/267/OG": {
    code: "FC/267/OG",
    name: "Abeokuta North/Obafemi-Owode/Odeda",
    race: "house",
    state_code: "OG",
    state_name: "Ogun",
  },
  "FC/268/OG": {
    code: "FC/268/OG",
    name: "Abeokuta South",
    race: "house",
    state_code: "OG",
    state_name: "Ogun",
  },
  "FC/269/OG": {
    code: "FC/269/OG",
    name: "Ado-Odo/Ota",
    race: "house",
    state_code: "OG",
    state_name: "Ogun",
  },
  "FC/270/OG": {
    code: "FC/270/OG",
    name: "Egbado North/Imeko-Afon",
    race: "house",
    state_code: "OG",
    state_name: "Ogun",
  },
  "FC/239/LA": {
    code: "FC/239/LA",
    name: "Lagos Island II",
    race: "house",
    state_code: "LA",
    state_name: "Lagos",
  },
  "FC/271/OG": {
    code: "FC/271/OG",
    name: "Egbado South/Ipokia",
    race: "house",
    state_code: "OG",
    state_name: "Ogun",
  },
  "FC/272/OG": {
    code: "FC/272/OG",
    name: "Ifo/Ewekoro",
    race: "house",
    state_code: "OG",
    state_name: "Ogun",
  },
  "FC/273/OG": {
    code: "FC/273/OG",
    name: "Ijebu North/Ijebu East/Ogun Waterside",
    race: "house",
    state_code: "OG",
    state_name: "Ogun",
  },
  "FC/274/OG": {
    code: "FC/274/OG",
    name: "Ijebu Ode/Odogbolu/Ijebu North East",
    race: "house",
    state_code: "OG",
    state_name: "Ogun",
  },
  "FC/275/OG": {
    code: "FC/275/OG",
    name: "Ikenne/Shagamu/Remo North",
    race: "house",
    state_code: "OG",
    state_name: "Ogun",
  },
  "FC/276/OD": {
    code: "FC/276/OD",
    name: "Akoko North East/Akoko North West",
    race: "house",
    state_code: "ON",
    state_name: "Ondo",
  },
  "FC/277/OD": {
    code: "FC/277/OD",
    name: "Akoko South East/Akoko South West",
    race: "house",
    state_code: "ON",
    state_name: "Ondo",
  },
  "FC/278/OD": {
    code: "FC/278/OD",
    name: "Akure North/Akure South",
    race: "house",
    state_code: "ON",
    state_name: "Ondo",
  },
  "FC/279/OD": {
    code: "FC/279/OD",
    name: "Idanre/Ifedore",
    race: "house",
    state_code: "ON",
    state_name: "Ondo",
  },
  "FC/280/OD": {
    code: "FC/280/OD",
    name: "Ileoluji/Okeigbo/Odigbo",
    race: "house",
    state_code: "ON",
    state_name: "Ondo",
  },
  "FC/281/OD": {
    code: "FC/281/OD",
    name: "Okitipupa/Irele",
    race: "house",
    state_code: "ON",
    state_name: "Ondo",
  },
  "FC/282/OD": {
    code: "FC/282/OD",
    name: "Eseodo/Ilaje",
    race: "house",
    state_code: "ON",
    state_name: "Ondo",
  },
  "FC/283/OD": {
    code: "FC/283/OD",
    name: "Ondo East/Ondo West",
    race: "house",
    state_code: "ON",
    state_name: "Ondo",
  },
  "FC/284/OD": {
    code: "FC/284/OD",
    name: "Owo/Ose",
    race: "house",
    state_code: "ON",
    state_name: "Ondo",
  },
  "FC/285/OS": {
    code: "FC/285/OS",
    name: "Irepodun/Olorunda/Osogbo/Orolu",
    race: "house",
    state_code: "OS",
    state_name: "Osun",
  },
  "FC/286/OS": {
    code: "FC/286/OS",
    name: "Odo-Otin/Ifelodun/Boripe",
    race: "house",
    state_code: "OS",
    state_name: "Osun",
  },
  "FC/287/OS": {
    code: "FC/287/OS",
    name: "Boluwaduro/Ifedayo/Ila",
    race: "house",
    state_code: "OS",
    state_name: "Osun",
  },
  "FC/288/OS": {
    code: "FC/288/OS",
    name: "Atakunmosa East/Atakunmosa West/Ilesha East/Ilesha West",
    race: "house",
    state_code: "OS",
    state_name: "Osun",
  },
  "FC/289/OS": {
    code: "FC/289/OS",
    name: "Obokun/Oriade",
    race: "house",
    state_code: "OS",
    state_name: "Osun",
  },
  "FC/290/OS": {
    code: "FC/290/OS",
    name: "Ife Central/Ife North/Ife South/Ife East",
    race: "house",
    state_code: "OS",
    state_name: "Osun",
  },
  "FC/291/OS": {
    code: "FC/291/OS",
    name: "Ayedire/Iwo/Ola-Oluwa",
    race: "house",
    state_code: "OS",
    state_name: "Osun",
  },
  "FC/292/OS": {
    code: "FC/292/OS",
    name: "Ayedaade/Irewole/Isokan",
    race: "house",
    state_code: "OS",
    state_name: "Osun",
  },
  "FC/293/OS": {
    code: "FC/293/OS",
    name: "Ede North/Ede South/Egbedore/Ejigbo",
    race: "house",
    state_code: "OS",
    state_name: "Osun",
  },
  "FC/294/OY": {
    code: "FC/294/OY",
    name: "Afijio/Oyo East/Oyo West/Atiba",
    race: "house",
    state_code: "OY",
    state_name: "Oyo",
  },
  "FC/295/OY": {
    code: "FC/295/OY",
    name: "Akinyele/Lagelu",
    race: "house",
    state_code: "OY",
    state_name: "Oyo",
  },
  "FC/296/OY": {
    code: "FC/296/OY",
    name: "Egbeda/Ona-Ara",
    race: "house",
    state_code: "OY",
    state_name: "Oyo",
  },
  "FC/297/OY": {
    code: "FC/297/OY",
    name: "Ibarapa Central/Ibarapa North",
    race: "house",
    state_code: "OY",
    state_name: "Oyo",
  },
  "FC/298/OY": {
    code: "FC/298/OY",
    name: "Ibarapa East/Ido",
    race: "house",
    state_code: "OY",
    state_name: "Oyo",
  },
  "FC/299/OY": {
    code: "FC/299/OY",
    name: "Saki East/Saki West/Atisbo",
    race: "house",
    state_code: "OY",
    state_name: "Oyo",
  },
  "FC/300/OY": {
    code: "FC/300/OY",
    name: "Irepo/Orelope/Olorunsogo",
    race: "house",
    state_code: "OY",
    state_name: "Oyo",
  },
  "FC/301/OY": {
    code: "FC/301/OY",
    name: "Iseyin/Itesiwaju/Kajola/Iwajowa",
    race: "house",
    state_code: "OY",
    state_name: "Oyo",
  },
  "FC/302/OY": {
    code: "FC/302/OY",
    name: "Ogbomoso North/Ogbomoso South/Orire",
    race: "house",
    state_code: "OY",
    state_name: "Oyo",
  },
  "FC/303/OY": {
    code: "FC/303/OY",
    name: "Ogo-Oluwa/Surulere",
    race: "house",
    state_code: "OY",
    state_name: "Oyo",
  },
  "FC/304/OY": {
    code: "FC/304/OY",
    name: "Oluyole",
    race: "house",
    state_code: "OY",
    state_name: "Oyo",
  },
  "FC/305/OY": {
    code: "FC/305/OY",
    name: "Ibadan North East/Ibadan South East",
    race: "house",
    state_code: "OY",
    state_name: "Oyo",
  },
  "FC/306/OY": {
    code: "FC/306/OY",
    name: "Ibadan South West/Ibadan North West",
    race: "house",
    state_code: "OY",
    state_name: "Oyo",
  },
  "FC/307/OY": {
    code: "FC/307/OY",
    name: "Ibadan North",
    race: "house",
    state_code: "OY",
    state_name: "Oyo",
  },
  "FC/308/PL": {
    code: "FC/308/PL",
    name: "Jos North/Bassa",
    race: "house",
    state_code: "PL",
    state_name: "Plateau",
  },
  "FC/309/PL": {
    code: "FC/309/PL",
    name: "Jos South/Jos East",
    race: "house",
    state_code: "PL",
    state_name: "Plateau",
  },
  "FC/310/PL": {
    code: "FC/310/PL",
    name: "Barkin Ladi/Riyom",
    race: "house",
    state_code: "PL",
    state_name: "Plateau",
  },
  "FC/311/PL": {
    code: "FC/311/PL",
    name: "Bokkos/Mangu",
    race: "house",
    state_code: "PL",
    state_name: "Plateau",
  },
  "FC/312/PL": {
    code: "FC/312/PL",
    name: "Kanke/Pankshin/Kanam",
    race: "house",
    state_code: "PL",
    state_name: "Plateau",
  },
  "FC/313/PL": {
    code: "FC/313/PL",
    name: "Wase",
    race: "house",
    state_code: "PL",
    state_name: "Plateau",
  },
  "FC/314/PL": {
    code: "FC/314/PL",
    name: "Langtang North/Langtang South",
    race: "house",
    state_code: "PL",
    state_name: "Plateau",
  },
  "FC/315/PL": {
    code: "FC/315/PL",
    name: "Mikang/Quaan/Pan/Shedam",
    race: "house",
    state_code: "PL",
    state_name: "Plateau",
  },
  "FC/316/RV": {
    code: "FC/316/RV",
    name: "Abua-Odual/Ahaoda East",
    race: "house",
    state_code: "RI",
    state_name: "Rivers",
  },
  "FC/317/RV": {
    code: "FC/317/RV",
    name: "Ahoada West/Ogba Egbema",
    race: "house",
    state_code: "RI",
    state_name: "Rivers",
  },
  "FC/318/RV": {
    code: "FC/318/RV",
    name: "Degema/Bonny",
    race: "house",
    state_code: "RI",
    state_name: "Rivers",
  },
  "FC/319/RV": {
    code: "FC/319/RV",
    name: "Akuku-Toru/Asari-Toru",
    race: "house",
    state_code: "RI",
    state_name: "Rivers",
  },
  "FC/320/RV": {
    code: "FC/320/RV",
    name: "Okrika/Ogu-Bolo",
    race: "house",
    state_code: "RI",
    state_name: "Rivers",
  },
  "FC/321/RV": {
    code: "FC/321/RV",
    name: "Opobo/Nkoro/Andoni",
    race: "house",
    state_code: "RI",
    state_name: "Rivers",
  },
  "FC/322/RV": {
    code: "FC/322/RV",
    name: "Eleme/Tai/Oyigbo",
    race: "house",
    state_code: "RI",
    state_name: "Rivers",
  },
  "FC/323/RV": {
    code: "FC/323/RV",
    name: "Khana/Gokana",
    race: "house",
    state_code: "RI",
    state_name: "Rivers",
  },
  "FC/324/RV": {
    code: "FC/324/RV",
    name: "Ikwerre/Umohua",
    race: "house",
    state_code: "RI",
    state_name: "Rivers",
  },
  "FC/325/RV": {
    code: "FC/325/RV",
    name: "Etche/Omuma",
    race: "house",
    state_code: "RI",
    state_name: "Rivers",
  },
  "FC/326/RV": {
    code: "FC/326/RV",
    name: "Obio Akpor",
    race: "house",
    state_code: "RI",
    state_name: "Rivers",
  },
  "FC/327/RV": {
    code: "FC/327/RV",
    name: "Port Harcourt I",
    race: "house",
    state_code: "RI",
    state_name: "Rivers",
  },
  "FC/329/SO": {
    code: "FC/329/SO",
    name: "Isa/Sabon Birni",
    race: "house",
    state_code: "SO",
    state_name: "Sokoto",
  },
  "FC/330/SO": {
    code: "FC/330/SO",
    name: "Goronyo/Gada",
    race: "house",
    state_code: "SO",
    state_name: "Sokoto",
  },
  "FC/331/SO": {
    code: "FC/331/SO",
    name: "Wurno/Rabah",
    race: "house",
    state_code: "SO",
    state_name: "Sokoto",
  },
  "FC/332/SO": {
    code: "FC/332/SO",
    name: "Illela/Gwadabawa",
    race: "house",
    state_code: "SO",
    state_name: "Sokoto",
  },
  "FC/333/SO": {
    code: "FC/333/SO",
    name: "Tangaza/Gudu",
    race: "house",
    state_code: "SO",
    state_name: "Sokoto",
  },
  "FC/334/SO": {
    code: "FC/334/SO",
    name: "Binji/Silame",
    race: "house",
    state_code: "SO",
    state_name: "Sokoto",
  },
  "FC/335/SO": {
    code: "FC/335/SO",
    name: "Kware/Wamakko",
    race: "house",
    state_code: "SO",
    state_name: "Sokoto",
  },
  "FC/336/SO": {
    code: "FC/336/SO",
    name: "Sokoto North/Sokoto South",
    race: "house",
    state_code: "SO",
    state_name: "Sokoto",
  },
  "FC/337/SO": {
    code: "FC/337/SO",
    name: "Dange-Shuni/Bodinga/Tureta",
    race: "house",
    state_code: "SO",
    state_name: "Sokoto",
  },
  "FC/338/SO": {
    code: "FC/338/SO",
    name: "Yabo/Shagari",
    race: "house",
    state_code: "SO",
    state_name: "Sokoto",
  },
  "FC/339/SO": {
    code: "FC/339/SO",
    name: "Kebbe/Tambuwal",
    race: "house",
    state_code: "SO",
    state_name: "Sokoto",
  },
  "FC/340/TR": {
    code: "FC/340/TR",
    name: "Bali/Gassol",
    race: "house",
    state_code: "TA",
    state_name: "Taraba",
  },
  "FC/341/TR": {
    code: "FC/341/TR",
    name: "Takum/Donga/Ussa",
    race: "house",
    state_code: "TA",
    state_name: "Taraba",
  },
  "FC/342/TR": {
    code: "FC/342/TR",
    name: "Sardauna/Kurmi/Gashaka",
    race: "house",
    state_code: "TA",
    state_name: "Taraba",
  },
  "FC/343/TR": {
    code: "FC/343/TR",
    name: "Ibi/Wukari",
    race: "house",
    state_code: "TA",
    state_name: "Taraba",
  },
  "FC/344/TR": {
    code: "FC/344/TR",
    name: "Jalingo/Yorro/Zing",
    race: "house",
    state_code: "TA",
    state_name: "Taraba",
  },
  "FC/345/TR": {
    code: "FC/345/TR",
    name: "Karim Lamido/Lau/Ardo-Kola",
    race: "house",
    state_code: "TA",
    state_name: "Taraba",
  },
  "FC/346/YB": {
    code: "FC/346/YB",
    name: "Bade/Jakusko",
    race: "house",
    state_code: "YO",
    state_name: "Yobe",
  },
  "FC/347/YB": {
    code: "FC/347/YB",
    name: "Bursari/Geidam/Yunusari",
    race: "house",
    state_code: "YO",
    state_name: "Yobe",
  },
  "FC/348/YB": {
    code: "FC/348/YB",
    name: "Damaturu/Gujba/Gulani/Tarmuwa",
    race: "house",
    state_code: "YO",
    state_name: "Yobe",
  },
  "FC/349/YB": {
    code: "FC/349/YB",
    name: "Fika/Fune",
    race: "house",
    state_code: "YO",
    state_name: "Yobe",
  },
  "FC/350/YB": {
    code: "FC/350/YB",
    name: "Machina/Nguru/Yusufari/Karasuwa",
    race: "house",
    state_code: "YO",
    state_name: "Yobe",
  },
  "FC/351/YB": {
    code: "FC/351/YB",
    name: "Nangere/Potiskm",
    race: "house",
    state_code: "YO",
    state_name: "Yobe",
  },
  "FC/352/ZF": {
    code: "FC/352/ZF",
    name: "Kaura-Namoda/Birnin Magaji",
    race: "house",
    state_code: "ZA",
    state_name: "Zamfara",
  },
  "FC/353/ZF": {
    code: "FC/353/ZF",
    name: "Shinkafi/Zurmi",
    race: "house",
    state_code: "ZA",
    state_name: "Zamfara",
  },
  "FC/354/ZF": {
    code: "FC/354/ZF",
    name: "Gusau/Tsafe",
    race: "house",
    state_code: "ZA",
    state_name: "Zamfara",
  },
  "FC/355/ZF": {
    code: "FC/355/ZF",
    name: "Bungudu/Maru",
    race: "house",
    state_code: "ZA",
    state_name: "Zamfara",
  },
  "FC/356/ZF": {
    code: "FC/356/ZF",
    name: "Anka/Talata Mafara",
    race: "house",
    state_code: "ZA",
    state_name: "Zamfara",
  },
  "FC/357/ZF": {
    code: "FC/357/ZF",
    name: "Bakura/Maradun",
    race: "house",
    state_code: "ZA",
    state_name: "Zamfara",
  },
  "FC/358/ZF": {
    code: "FC/358/ZF",
    name: "Gummi/Bukkuyum",
    race: "house",
    state_code: "ZA",
    state_name: "Zamfara",
  },
};
